const path = require('path');
const http = require('http');
const express = require('express');
const routing=require('./routing');
const PORT = process.env.PORT ||5123;
const cors = require('cors');
const cookieParser = require('cookie-parser');
var app = express();
let server = http.createServer(app,{cookie: true});
var logger= require('./logger');
module.exports=server;
app.use(cors());
app.use(cookieParser('Sai@2o00'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(__dirname + '/public'));
app.use(express.static(__dirname + '/node_modules'));
app.use(routing);
server.listen(PORT,function(){
  logger.info(`Server is up on port ${PORT}`);
  console.log(`Server is up on port ${PORT}`);
});
require('./socket');